# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.configuration-cache=true

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=26.2
loader_version=0.19.5
loom_version=1.18.2

# Mod Properties
version=1.0.0
group=io.github.harryforest2003
archives_base_name=svm-subtitles

# Dependencies
fabric_api_version=0.161.0+26.2
voicechat_api_version=2.6.24
voicechat_version=fabric-2.6.24+26.2
whisper_jni_version=1.7.1
